import Head from 'next/head'
import Header from '../Components/Header'
import Login from '../Components/Login'
import Sidebar from '../Components/Sidebar'
import {getSession} from 'next-auth/react'
import Feed from  '../Components/Feed'
import Widgets from  '../Components/Widgets'
import {db} from '../firebase';



export default function Home({session, posts}) {
  if(!session) return <Login/>;
  return (
    <div
    className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <main className="flex">
      <Sidebar/>
      <Feed posts={posts}/>
      <Widgets/>

      </main>

    </div>
  )
}

export async function getServerSideProps(context){
  //get the UserGroupIcon
  const session = await getSession(context);
  const posts = await db.collection("posts").orderBy("timestamp","desc").get();
  const docs=posts.docs.map(post =>({
    id:post.id,
    ...post.data(),
    timestamp: null
  }))
  return{
    props:{
      session,
      posts:docs,
    },
  };
}
